version: "3.8"
services:

  #  app:
#    build: .
#    ports:
#      - '8081:8080'

  flyway:
    image: flyway/flyway:10-alpine
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
      - ./.docker/flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres

  postgres:
    container_name: "postgres-skip"
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=courier-statement'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/

  localstack:
    image: localstack/localstack:3.0.2
    container_name: localstack-skip
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".docker/docker-entrypoint.sh/:/docker-entrypoint-initaws.d/docker-entrypoint.sh"

#  k6:
#    image: mostafamoradian/xk6-kafka:0.22.0
#    command: k6 run queue-script.js
##    command: ["sleep ","infinity"]
#    networks:
#      - broker-kafka
#    depends_on:
#      - kafka
#    volumes:
#      - ./k6:/~

networks:
  broker-kafka:
    driver: bridge
